### ISSUE TITLE
Still not working for Sketch 42

### ISSUE THREAD

**Issue by TurboDingus** [hrescak/Sketch-Layer-Tools#12]
all scripts are still not working on Sketch 42. :(

**Comment by hrescak** [comment]
Hi TurboDingus, which ones are not working? I just tried a couple and those worked.

**Comment by TurboDingus** [comment]
Hey hrescak! Thanks for your reply. Here is a video of me trying to use the select same fill color script. Perhaps I'm not using it the way it was intended. I haven't use much of the other scripts. I really needed the select same fill and select same boarder to repair some designs that haven been formatted correctly.

https://www.dropbox.com/s/04rkyvmv2r9v1vz/Select%20Same%20Fill%20Color.mp4?dl=0

**Comment by hrescak** [comment]
I can reproduce that - I'll take a look at updating this weekend

**Comment by TurboDingus** [comment]
hrescak, thanks so much! Please post your donation link if you have one after its resolved :)
